apiVersion: v1
kind: Secret
metadata:
  name: dockerconfigjson
  namespace: cinemaabyss
data:
  .dockerconfigjson: ewoJImF1dGhzIjogewoJCSJnaGNyLmlvIjogewoJCQkiYXV0aCI6ICJjMkZqYUdGcmF6TTZaMmwwYUhWaVgzQmhkRjh4TVVGRFFVY3pNMEV3ZFhneWNrRkJNMkpYU21kM1gzWmhaV2R5UjNWMmVrWnRXRUpyZDJ0cE9GZFlWWFl5YW5kM1JtTTNVSHBIT0RkV1JFOUtOakpTUzJKWFIwMDJUa1pPUkhSSVptSkVVakkyIgoJCX0sCgkJInJlZ2lzdHJ5LWdpdC5oaWx0aS5jb20iOiB7CgkJCSJhdXRoIjogIlFXeGxlR0Z1WkdWeUxrdDFjSEpwYXpveldsUjVUalk0Y3pkb01tRktRMHRCY1V0blJBPT0iCgkJfQoJfQp9
type: kubernetes.io/dockerconfigjson
